package br.com.desafio.infrastructure.model;

import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAttribute;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAutoGeneratedKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBHashKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBTable;

import lombok.Builder;
import lombok.Data;

@Data
@Builder
@DynamoDBTable(tableName = "planet")
public class Planet {
    
	@DynamoDBHashKey
    @DynamoDBAutoGeneratedKey
    private String id;
	
	@DynamoDBAttribute
    private String nome;
	
	@DynamoDBAttribute
    private String clima;
	
	@DynamoDBAttribute
    private String terreno;

    public String getId() {
        return this.id;
    }
    
    public String getNome() {
        return this.nome;
    }
   
    public String getClima() {
        return this.clima;
    }
   
    public String getTerreno() {
        return this.terreno;
    }
    
    public void setId(String id) {
        this.id = id;
    }
    
    public void setNome(String nome) {
        this.nome = nome;
    }
   
    public void setClima(String clima) {
        this.clima = clima;
    }
   
    public void setTerreno(String terreno) {
        this.terreno = terreno;
    }
}