package br.com.desafio.infrastructure.model;

import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAttribute;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAutoGeneratedKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBHashKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBTable;

import lombok.Data;

@Data
@DynamoDBTable(tableName = "planet")
public class Planet {
    
	@DynamoDBHashKey
    @DynamoDBAutoGeneratedKey
    private String id;
	
	@DynamoDBAttribute
    private String nome;
	
	@DynamoDBAttribute
    private String clima;
	
	@DynamoDBAttribute
    private String terreno;
}